apps/calificacion/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from . import views


urlpatterns = [
	url(r'index',views.inicio,name="inicio"),	
    url(r'sociodemografico_2', views.sociodemografico_2 ,name="sociodemografico_2"),
    url(r'FormaA', views.formaA ,name="FormaA"),
    url(r'FormaB', views.formaA ,name="FormaB"),
    url(r'municipios/', views.get_municipios,name="municipios"),
    url(r'cargo/',views.add_cargo,name="cargo"),
    url(r'area/',views.add_area,name="area"),
    url(r'profesion/',views.add_profesion,name="profesion"),
]

bateria2_7/urls.py
from django.contrib import admin
from django.conf.urls import url,include

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'',include(('apps.calificacion.urls','calificacion'),namespace="index")),
]

templates/BateriaFinalizada.html
{% extends 'base.html' %}

{% block content %}
{% load staticfiles %}

	<div class="container-fluid">
		<div class="col-md-12 p-6 bg-light">

			<div class="row">
				<div class="col-md-6 offset-md-3">
					<h5 class="text-center text-uppercase" style="color: green"> Resultados guardados exitosamente </h5>
					<table class="table table-striped">

						<tr>
							<td>Nombre</td>
							<td>{{request.session.datos_trabajador_nombre}}</td>
						</tr>
						<tr>

							<td>Cedula</td>
							<td> {{request.session.datos_trabajador_cedula}}<td>
						</tr>
						<tr>
							<td>Nombre de la empresa</td>
							<td> {{request.session.datos_trabajador_nombre_empresa}}<td>

						</tr>									
					</table>
					<div class="col-md-12 text-center">
						<a id="nueva" class="btn btn-lg btn-info" href="{% url 'index:inicio' %}" >Calificar otra bateria</a>
						<a onclick="cambio()" class="btn btn-lg btn-success" href="{{request.session.url_grafica}}" target="_blank">Registrar Datos</a>
					</div>
				</div>
		    </div>
	</div>
	
	
<script type="text/javascript">
	$("#nueva").hide();
	function cambio(){
			$("#nueva").show();
	}
</script>

{%endblock%}

templates/SinEscaner.html
{% extends 'base.html' %}

{% block content %}
{% load staticfiles %}

	<div class="container-fluid">
		<div class="col-md-12 p-6 bg-light">

			<div class="row">
				<div class="col-md-6 offset-md-3">
					<h5 class="text-center text-uppercase" style="color: orangered"> {{mensaje}}</h5>
					
					<div class="col-md-12 text-center">
						<a class="btn btn-lg btn-warning" href="{% url 'index:inicio' %}" >Volver</a>
					</div>
				</div>
		    </div>
	</div>
	
	

{%endblock%}

templates/add_area.html
{% extends 'base.html' %}

{% block content %}
{% load staticfiles %}
<div class="row">
	<div class="col-md-12 text-center">
		<h1 class="text-uppercase">Modulo de creacion de areas en la empresa</h1>
		<p style="color:green">{{mensaje}}</p>
		<form class="form" method="POST">
			{% csrf_token %}
			<label> Escriba el nombre del cargo a crear</label>
			<div class="col-md-6 offset-md-3">
				<input type="text" name="nombre" required class="text-uppercase form-control">
			</div>
			<br>
			<button type="submit" class="btn btn-success btn-lg"> Crear</button>
			
		</form>
		
	</div>
	
</div>
{%endblock%}

templates/add_cargo.html
{% extends 'base.html' %}

{% block content %}
{% load staticfiles %}
<div class="row">
	<div class="col-md-12 text-center">
		<h1 class="text-uppercase">Modulo de creacion de cargos</h1>

		<p style="color:green">{{mensaje}}</p>
		<form class="form">
		{% csrf_token %}
			<label> Escriba el nombre del cargo a crear</label>
			<div class="col-md-6 offset-md-3">
				<input type="text" name="nombre" required class="text-uppercase form-control">
			</div>
			<br>
			<button type="submit" class="btn btn-success btn-lg"> Crear</button>
			
		</form>
		
	</div>
	
</div>
{%endblock%}

templates/add_profesion.html
{% extends 'base.html' %}

{% block content %}
{% load staticfiles %}
<div class="row">
	<div class="col-md-12 text-center">
		<h1 class="text-uppercase">Modulo de creacion de profesiones</h1>

		<p style="color:green">{{mensaje}}</p>
		<form class="form">
		{% csrf_token %}
			<label> Escriba el nombre del profesion a crear</label>
			<div class="col-md-6 offset-md-3">
				<input type="text" name="nombre" required class="text-uppercase form-control">
			</div>
			<br>
			<button type="submit" class="btn btn-success btn-lg"> Crear</button>
			
		</form>
		
	</div>
	
</div>
{%endblock%}

templates/base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
	<title>Bateria de riego Psicosocial Proteger I.P.S</title>
	<link rel="icon" type="image/png" href="{% static 'image/favicon.png' %}">
</head>
<script
  src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
  crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<body>

{% block header %}


	<nav class="navbar navbar-expand-lg navbar-light bg-light">
	  <a class="navbar-brand" href="/index"><img src="{% static 'image/logo.png' %}"></a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>


	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav mr-auto">
	     
	      <li class="nav-item dropdown">
	        <a class="nav-link dropdown-toggle text-uppercase"  href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	          Agregar Información

	        </a>
	        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
	        	<a class="dropdown-item" href="{% url 'index:profesion' %}">Agregar una profesion</a>
	          <a class="dropdown-item" href="{% url 'index:cargo' %}">Agregar cargo</a>
	          <a class="dropdown-item" href="{% url 'index:area' %}">Agregar area de la empresa</a>
	          <div class="dropdown-divider"></div>
	          
	        </div>
	      </li>
	    
	    </ul>
	    
	  </div>
	  <p>BATERIA DE RIESGO PSICOSOCIAL</p>
	</nav>
{% endblock %}

{% block content %}
{% endblock %}

</body>
</html>

templates/formaA.html
{% extends 'base.html' %}

{% block content %}
{% load staticfiles %}

	<div class="container-fluid">
		<div class="col-md-6 offset-md-3 text-center mb-6">


				<h5 class="text-center text-uppercase">
						Por favor verfica que la imagen corresponde a la <span style="color:orangered"> HOJA DE RESPUESTAS {{request.session.url_tipo_forma}}</span> y que los siguientes datos son correctos
					</h5>
				<!-- <p style="color:orangered">Antes de iniciar la lectura de las baterias de riesgo, por favor diligencie los siguientes datos.</p> -->
			</div>
		<div class="row">
			
		<div class="col-md-12 p-6">

			<div class="row">
				<div class="col-md-6">
					<h4>{{request.session.url_tipo_forma}}</h4>
					<table class="table table-striped text-center">
						<tr>
						<td> # PREGUNTA</td>
						<td> RESPUESTA</td>
						<td> VALOR NUMERICO</td>
					</tr>
						{% for forma in formaA%}
							<tr style="font-size: 12px">
							    <td>{{forma.2}}</td>
								 <td>{{forma.0}}</td>
								 <td>{{forma.1}}</td>
								 
							</tr>

						{%endfor%}
 
					</table>
				<h4>Extralaboral</h4>
				<table class="table table-striped text-center">
						<tr>
						<td> # PREGUNTA</td>
						<td> RESPUESTA</td>
						<td> VALOR NUMERICO</td>
					</tr>
						{% for forma in Extralaboral%}
							<tr style="font-size: 12px">
							    <td>{{forma.2}}</td>
								 <td>{{forma.0}}</td>
								 <td>{{forma.1}}</td>
								 
							</tr>

						{%endfor%}
 
					</table>

				<h4>Estres</h4>

					<table class="table table-striped text-center">
						<tr>
						<td> # PREGUNTA</td>
						<td> RESPUESTA</td>
						<td> VALOR NUMERICO</td>
					</tr>
						{% for forma in Estres%}
							<tr style="font-size: 12px">
							    <td>{{forma.2}}</td>
								 <td>{{forma.0}}</td>
								 <td>{{forma.1}}</td>
								 
							</tr>

						{%endfor%}
 
					</table>


				</div>


				<div class="col-md-6 bg-light" style="border:2px green solid;padding:5%">
					<h6 class="text-center">Imagen Escaneada <span style="color:orangered">"{{request.session.url_tipo_forma}}"</span></h6>
					<img src="{% static form.url%}" width="100%">
					<div class="col-md-12 text-center">
						<form method="post">
						{% csrf_token %}
						<input type="hidden" name="cambio_img">
						<button type="submit" class="btn btn-warning btn-lg" >Si los datos no corresponden por favor   
						<span style="color:orangered" class="text-uppercase"> ESCANEA DE NUEVO LA HOJA "DATOS GENERALES {{request.session.url_tipo_forma}}" Y LUEGO CLICK AQUI PARA CAMBIAR LA IMAGEN</span></button>
					</form>
						<br>
							<form method="post">
								{% csrf_token %}
								<input type="hidden" name="CheckFormA"> 
								<br>
								<button type="submit" class="btn btn-lg btn-success">Confirmar y Guardar Datos de {{request.session.datos_trabajador_nombre}} </button>
								
							</form>
						</div>
				</div>
		</div>


	</div>
	

{%endblock%}

templates/index.html
{% extends 'base.html' %}

{% block content %}
{% load staticfiles %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.10/js/select2.min.js"></script>

	<div class="container-fluid">
		<div class="row">
			<div class="col-md-12 text-center">

				
				<!-- <p style="color:orangered">Antes de iniciar la lectura de las baterias de riesgo, por favor diligencie los siguientes datos.</p> -->
			</div>
		<div class="col-md-12 p-6">
			
			<div class="col-md-6 offset-md-3 text-justify bg-light">
					<h4 class="text-center text-uppercase"> Bienvenido al software para calificacón de la bateria de riesgo psicosocial desarrollado por Proteger I.P.S</h4>

			</div>
			<div class="col-md-12" style="border:2px black solid;padding: 3%"> 
				<h5 class="text-center text-uppercase text-info"> ASEGURECE DE ESCANEAR LAS TRES CARAS DE LA BATERIA DEL PACIENTE A CALIFICAR</h5>
				<br>

	{% if form %}


				<p class="text-center" style="color:orangered"><b>Empiece por diligenciar los siguientes datos, estos datos estan en la primera cara de la Ficha de datos generales y fueron suministrados por el paciente </b></p>
				{% if successSave %}
					<p class="text-center text-success">{{successSave}}</p>
				{%endif%}
				
			
		<div class="row">
				<div class="col-md-6">
					<div class="bg-info p-4 text-center"> 
					<label style="font-weight: bold"> Fecha de aplicacion de la bateria </label>
					
					{% if request.session.datos_trabajador_fecha_aplicacion %}
						<input type="date" value="{{request.session.datos_trabajador_fecha_aplicacion}}" name="aplicacion_fecha" class="form-control" required>
					{% else %}
						<input type="date" name="aplicacion_fecha" class="form-control" required>
					{% endif %}

					<label style="font-weight: bold"> Nombre de la empresa </label>
					{% if request.session.datos_trabajador_nombre_empresa %}
						<input type="text"  value="{{request.session.datos_trabajador_nombre_empresa}}" name="empresa" class="form-control text-uppercase" required>
					{% else %}
						<input type="text"  name="empresa" class="form-control" required>
					{% endif %}
				</div>

					<label for="nombre_paciente">Nombre del trabajador</label>	

					<input type="text" name="nombre_paciente"  class="form-control text-uppercase" required>

					<p for="departamento_trabajo">Departamento en el que trabaja actualmente</p>
					<select name="departamento_trabajo" class="form-control text-uppercase" onchange="departamento2(this)">
						<option></option>
						{% for departamento in departamentos%}
						<option value="{{departamento.id_departamento}}">{{departamento.departamento}}</option>
						{% endfor %}
					</select>

					</select>
					<p for="municipio_trabajo">Municipio en el que trabaja actualmente</p>
					<select name="municipio_trabajo" class="form-control text-uppercase" id="municipio_trabajo_id">
						
					</select>
					
				</div>
				<div class="col-md-6">
					<label for="departamento_trabajo">Departamento en el que vive actualmente</label>
										
					<select name="departamento_vivienda" class="form-control" onchange="departamento(this)" required>
						<option></option>
						{% for departamento in departamentos%}
						<option value="{{departamento.id_departamento}}">{{departamento.departamento}}</option>
						{% endfor %}
					</select>

					
					<label for="municipio_vivienda">Municipio en el que vive actualmente</label>
					<select name="municipio_vivienda" class="form-control" id="municipio_vivienda_id" required>

					</select>

					<label for="profesion">¿ Cual es su ocupacion o profesion?</label>
					<select class="form-control" name="profesion" required>
						<option></option>
						{% for profesion in profesiones%}
							<option class="text-uppercase"> {{profesion.nombre}}</option>
						{% endfor %}

					</select>

					
					<label for="cargo">¿ Cual es el nombre del cargo que ocupa en la empresa ?</label>
					<select class="form-control" name="cargo" required>
						<option></option>
						{% for cargo in cargos%}
							<option> {{cargo.nombre}}</option>
						{% endfor %}

					</select>
					
					<label>Nombre del departamento area o seccion de la empresa en el que trabaja</label>
					<select class="form-control" name="area" required>
						<option></option>
						{% for area in areas%}
							<option> {{area.nombre}}</option>
						{% endfor %}

					</select>
				
				</div>
				</div>
		{% endif %}
					<br>
					<form class="form" enctype="multipart/form-data" method="post">
					{% csrf_token %}
					<div class="col-md-12 text-center mt-4 mb-12">
						<button type="submit" class="btn btn-lg btn-success p-5">Calificar Ficha De Datos Generales Cara Uno </button>
					</div>

					</form>
						

				</div>

				</div>
		</div>

	</div>

<script type="text/javascript">
	function departamento(departamento){
		console.log("Llamado")
		$('#municipio_vivienda_id').html("")
		$.ajax({
				url:'/index/municipios',
				dataType:'json',
				data:{departamento_id:departamento.value},
				success:(data)=>{
					data.forEach((municipios)=>{
						
						$('#municipio_vivienda_id').append("<option class='text-uppercase'>"+municipios.fields.municipio+"</option>")

					})
					
				}

			})
	}

	function departamento2(departamento){
		console.log("Llamado")
		$('#municipio_trabajo_id').html("")
		$.ajax({
				url:'/index/municipios',
				dataType:'json',
				data:{departamento_id:departamento.value},
				success:(data)=>{
					data.forEach((municipios)=>{
						
						$('#municipio_trabajo_id').append("<option class='text-uppercase'>"+municipios.fields.municipio+"</option>")

					})
					
				}

			})
	}

	
	
		

</script>

{%endblock%}

templates/sociodemografico_1.html
{% extends 'base.html' %}

{% block content %}
{% load staticfiles %}

	<div class="container-fluid">
		<div class="row">
			<div class="col-md-6 offset-md-3 text-center p-4">
				
				<h5 class="text-center text-uppercase">
						Por favor verfica que la imagen corresponde a la <span style="color:orangered"> CARA UNO DE LA FICHA DE DATOS GENERALES</span> y que los siguientes datos son correctos
					</h5>
				
				<!-- <p style="color:orangered">Antes de iniciar la lectura de las baterias de riesgo, por favor diligencie los siguientes datos.</p> -->
			</div>
		<div class="col-md-12 p-6 ">

			<div class="row">
				<div class="col-md-6">
					
					<table class="table table-striped">

						<tr>
							<td>Nombre</td>
							<td>{{ request.session.datos_trabajador_nombre }}</td>
						</tr>
						<tr>

							<td>Ultimo nivel de estudios que alcanzo</td>
							<td> {{ request.session.datos_trabajador_nivel_estudio }}</td>
						</tr>
							<tr>
							<td>Cedula</td>
							<td>{{ request.session.datos_trabajador_cedula }}</td>
						</tr>
						<tr>
							<td>Año de nacimiento</td>
							<td>{{ request.session.datos_trabajador_ano_nacimiento }}</td>
						</tr>

						<tr>

							<td>Estado Civil</td>
							<td>{{ request.session.datos_trabajador_estado_civil }}</td>
						</tr>
						<tr>

							<td>Estrato</td>
							<td>{{ request.session.datos_trabajador_estrato }}</td>
						</tr>
						<tr>

							<td>Tipo de vivienda</td>
							<td>{{ request.session.datos_trabajador_tipo_vivienda }}</td>
						</tr>
						<tr>
							<td>Sexo</td>
							<td>{{ request.session.datos_trabajador_sexo }}</td>
						</tr>

						<tr>
							<td>Profesion u ocupación</td>
							<td>{{ request.session.datos_trabajador_profesion }}</td>
						</tr>

						<tr>
							<td>Numero de personas que dependen economicamente del trabajador</td>
							<td>{{ request.session.datos_trabajador_personas_dependientes }}</td>
						</tr>

						<tr>
							<td>Departamento donde trabaja actualmente </td>
							<td>{{ request.session.dept }}</td>
						</tr>
						<tr>
							<td>Municipio donde trabaja actualmente </td>
							<td>{{ request.session.ciut }}</td>
						</tr>

						<tr>
							<td>Departamento de residencia actual</td>
							<td>{{ request.session.depr }}</td>
						</tr>

						<tr>
							<td>Municipio de residencia actual</td>
							<td>{{ request.session.ciur }}</td>
						</tr>
						<tr>

							<td>Hace cuantos años trabaja en la empresa</td>
							<td>{{ request.session.datos_trabajador_duracion_empresa }}</td>
						</tr>
						<tr>
							<td>Tipo de cargo</td>
							<td>{{ request.session.datos_trabajador_tipo_cargo }}</td>
						</tr>
						<tr>
							<td>Nombre del cargo que ocupa el trabajador</td>
							<td>{{ request.session.cargo }}</td>
						</tr>
						
						
						
						
						
					</table>
					
					<div class="col-md-12 text-center">
						<form method="post" class="form" enctype="multipart/form-data" action="{% url 'index:sociodemografico_2' %}"> 
							{% csrf_token %}
						<div class="row">	
						<div class="col-md-6">

							<label>¿ Los datos de la cara uno de la ficha de datos generales son correctos ?</label>
						</div>
						<div class="col-md-6">
							<input type="checkbox" name="" required class="form-control">
						</div>
						</div>
						<!-- <div class="bg-info p-3 m-3">
							<h6> Por favor suba la <span style="color:#303030" class="text-uppercase">Cara dos de la ficha de datos generales</span> de {{ request.session.datos_trabajador_nombre }}</h6>
							<input type="file" name="sociodemografico_segunda">
						</div> -->
							<button type="submit" class="btn btn-success"> CALIFICAR SEGUNDA CARA FICHA DE DATOS GENERALES</button>
							
						</form>
						
					</div>
				</div>

				<div class="col-md-6 bg-light" style="border:2px green solid;padding:5%">
					<h6 class="text-center">Imagen Escaneada <span style="color:orangered">"Datos Generales Cara Uno"</span></h6>
					<img src="{% static form.url%}" width="100%">
					<div class="text-center">
					<form method="post">
						{% csrf_token %}
						<input type="hidden" name="cambio_img">
						<button type="submit" class="btn btn-warning btn-lg" >Si los datos no corresponden por favor   
						<span style="color:orangered"> ESCANEA DE NUEVO LA HOJA "DATOS GENERALES CARA UNO" Y LUEGO CLICK AQUI PARA CAMBIAR LA IMAGEN</span></button>
					</form>
					</div>
				</div>
		</div>
<br>
<br>
<br>
<br>
	</div>
	

{%endblock%}

templates/sociodemografico_2.html
{% extends 'base.html' %}

{% block content %}
{% load staticfiles %}

	<div class="container-fluid">
		<div class="row">
			<div class="col-md-6 offset-md-3 text-center mb-6">


				<h5 class="text-center text-uppercase">
						Por favor verfica que la imagen corresponde a la <span style="color:orangered"> CARA DOS de la ficha de datos generales
						</span> y que los siguientes datos son correctos
					</h5>
				<!-- <p style="color:orangered">Antes de iniciar la lectura de las baterias de riesgo, por favor diligencie los siguientes datos.</p> -->
			</div>
		<div class="col-md-12 p-6 bg-light">

			<div class="row">
				<div class="col-md-6">
					
					<table class="table table-striped">

						<tr>
							<td>Hace cuantos años desempeña el cargo u oficio actual</td>
							<td>{{request.session.datos_trabajador_duracion_cargo}}</td>
						</tr>
						<tr>

							<td>Nombre del departamento o area de la empresa en que trabaja</td>
							<td> {{request.session.datos_trabajador_area}}<td>
						</tr>
						<tr>
							<td>Tipo de contrato</td>
							<td> {{request.session.datos_trabajador_tipo_contrato}}<td>

						</tr>
						<tr>
							<td>Horas diarias trabajadas</td>
							<td> {{request.session.datos_trabajador_horas_diarias}}<td>
						</tr>

						<tr>

							<td>Tipo de salario</td>
							<td> {{request.session.datos_trabajador_tipo_salario}}<td>
						</tr>
									
	
					</table>
					
					<div class="col-md-12 text-center">
						<form method="post" class="form" enctype="multipart/form-data" action="{{request.session.url_tipo_forma}}"> 
							{% csrf_token %}
							<div class="row">
								<div class="col-md-6">
									<label>¿ Los datos de la cara uno de la ficha de datos generales son correctos ?</label>
								</div>
								<div class="col-md-6"> 
									<input type="checkbox" name="" required class="form-control">
								</div>
							</div>
						
						<div class="col-md-12 bg-info p-5 mb-6">
							<!-- <p class="text-uppercase"> Por favor seleccione la hoja de respuestas {{request.session.url_tipo_forma}} de <span style="color:#303030;font-weight: bold">{{request.session.datos_trabajador_nombre}}</span></p>
							<br>
							<input type="file" name="formaA"> -->
						</div>
						<br>
							<button type="submit" class="btn btn-success text-uppercase"> SUBIR FORMULARIO TIPO {{request.session.url_tipo_forma}}</button>
							
						</form>
						
					</div>
				</div>

				<div class="col-md-6 bg-light" style="border:2px green solid;padding:5%">
					<h6 class="text-center">Imagen Escaneada <span style="color:orangered">"Datos Generales Cara Dos"</span></h6>
					<img src="{% static form.url%}" width="100%">
					<div class="text-center">
						<form method="post">
						{% csrf_token %}
						<input type="hidden" name="cambio_img">
						<button type="submit" class="btn btn-warning btn-lg" >Si los datos no corresponden por favor   
						<span style="color:orangered"> ESCANEA DE NUEVO LA HOJA "DATOS GENERALES CARA DOS" Y LUEGO CLICK AQUI PARA CAMBIAR LA IMAGEN</span></button>
					</form>
					</div>
				</div>
		</div>


	</div>
	

{%endblock%}